<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Doctrine\ODM\MongoDB\MongoDBException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{
    public function GetUserForAdmin($id)
    {
        $user = array();
        try {
            $user = $this->createQueryBuilder()
                ->select("id", "username", "roles", "email")
                ->field('created_by')->equals($id)
                ->getQuery()
                ->execute();
        } catch (MongoDBException $e) {

        }

        return $user;
    }

    public function verifierUser($email, $username)
    {
        $users = array();
        try {
            $qb = $this->createQueryBuilder();
            $users = $qb->select("id")
                ->addOr(
                    $qb->expr()->field('email')->equals($email))
                ->addOr(
                    $qb->expr()->field('username')->equals($username)
                )
                ->getQuery()
                ->execute();
        } catch (MongoDBException $e) {
        }

        return count($users) == 0;
    }
}
