app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
api:
    resource: '@ApiBundle/Controller/'
    prefix: /api
    type: rest

api_login_check:
    path: /api/login_check
