<?php

namespace Api\ApiBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends DocumentRepository
{
}
