<?php

namespace Api\ApiBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MachineRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class MachineRepository extends DocumentRepository
{
}
